export const LOGIN = "LOGIN";
export const BAD_LOGIN = "BAD_LOGIN";
export const USERNAME_CHANGED = "USERNAME_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const NEW_TITLE_CHANGED = "NEW_TITLE_CHANGED";
